### ISSUE TITLE
Can't set up local development environment with SQLite

### ISSUE THREAD

**Issue by mikeconley** [WatchPeopleCode/WatchPeopleCode#10]
Hello,

I want to contribute to this project, but I'm having a hard time setting up my development environment; particularly, it looks like some of the migrations don't work with SQLite. For example, running upgrade 177b55430b61 -> 1aaef862b2da, I get:

sqlalchemy.exc.OperationalError: (OperationalError) Cannot add a NOT NULL column with default value NULL u'ALTER TABLE stream ADD COLUMN channel VARCHAR(25) NOT NULL' ()

If SQLite support isn't in the cards, which database backend should I be using instead to contribute?

**Comment by elimohl** [comment]
I think you can just run `db.create_all()` and then set `alembic_version` to last revision in your database.

**Comment by paked** [comment]
Just going to interject as someone who has tried and failed at setting up a
WPC Site development environment:
Is there a specific script to just do this? And if there is, could it be
placed somewhere a bit more obvious (ie, root directory)?

This is the kind of thing that could be added to the README file.

**Comment by eleweek** [comment]
No, there is no script. You could just launch python shell, type `from app import *` and then do `db.create_all()`

**Comment by elimohl** [comment]
I think REAME resolved it.
If you still has problem with databse, you can comment about it.

**Comment by mikeconley** [comment]
Yes agreed - thank you.
