### ISSUE TITLE
DateTime in the API for upcoming streams

### ISSUE THREAD

**Issue by lurraca** [WatchPeopleCode/WatchPeopleCode#19]
I know there's an open issue #12 for a proper REST API. But I'm not sure if that's something that will be worked on or not (it should imho).

In the meantime I would like to ask for the inclusion of the datetime fields for the upcoming streams in the  streams json.

**Current JSON:**

```
{
  "completed": [
    {
       ...
    }
  ],
  "live": [
    {
      ...
    }
  ],
  "upcoming": [
    {
      "title": "Interpreter development", 
      "url": "http://www.twitch.tv/raoulvdberge", 
      "username": "Raaaoul", 
      "viewers": null
    }
  ] 
}
```

**Proposed JSON:**

```
{
  "completed": [
    {
       ...
    }
  ],
  "live": [
    {
      ...
    }
  ],
  "upcoming": [
    {
      "title": "Interpreter development", 
      "url": "http://www.twitch.tv/raoulvdberge", 
      "username": "Raaaoul", 
      "viewers": null,
      "start_date": 2015-04-09 19:00 UTC
    }
  ] 
}
```

**Comment by eleweek** [comment]
I've just added actual_start_time and scheduled_start_time to the api, check it out: http://www.watchpeoplecode.com/json

I'll be happy to adjust the api if nessary.

**Comment by paked** [comment]
Everyone +1 #12 if you want a proper JSON API, I'd be happy to hack it together if people are interested

**Comment by eleweek** [comment]
Ok, closing it, since I implemented it yesterday. LMK if there are problems
