### ISSUE TITLE
Subscribe notification close region blocked by "Fork me" corner graphic

### ISSUE THREAD

**Issue by mavinger** [WatchPeopleCode/WatchPeopleCode#2]
Very minor issue but thought I would mention this. When you subscribe for updates via email the "you've subscribed successfully" notification close button is blocked by the "Fork me on GitHub" corner graphic. Clicking the 'X' takes you to GitHub.

![2015-02-11 09_56_56-watch people code](https://cloud.githubusercontent.com/assets/4130427/6149205/0b9de61c-b1d5-11e4-8b10-6300570f7713.png)

**Comment by eleweek** [comment]
Hi, thank you! We'll look at it.

**Comment by elimohl** [comment]
fixed
