### ISSUE TITLE
api/v1/streams/completed is not returning all data you see in the wpc site?

### ISSUE THREAD

**Issue by palaniraja** [WatchPeopleCode/WatchPeopleCode#22]
Hi,

Thanks for making api for it. I'm kind of getting my hand dirty with React-Native and the api. And I notice that the results in wpc site and the api are different?

Let me know if I miss anything.

**Comment by eleweek** [comment]
Hmm, it should return the same youtube streams(+ completed twitch streams). Could you please show an example?

**Comment by palaniraja** [comment]
Sorry, It is my mistake. The sort order of site & api is not same i suppose. Did a quick search for stream title and found them in the api. 

I swear i did the same other day but didn't return any results. Will keep you posted on my app progress.

Thanks again.
