### ISSUE TITLE
Pressing "popout chat" duplicates the streamer's window.

### ISSUE THREAD

**Issue by gkbrk** [WatchPeopleCode/WatchPeopleCode#37]
Happens on Linux/Firefox.

**Comment by eleweek** [comment]
Is it something that is possible to fully fix? it seems like twitch has the same issue(though it hides chat on the page when you press pop out)

**Comment by gkbrk** [comment]
I doesn't happen on Twitch for me. What happens is when I press "Popout chat", the chat window opens and the streamer page duplicates. So there's;
1. The original streamer window
2. The duplicated streamer window
3. The popout chat window

**Comment by eleweek** [comment]
Oh, this shouldn't happen! I'll look into it

**Comment by eleweek** [comment]
Fixed!
