### ISSUE TITLE
Better JSON API

### ISSUE THREAD

**Issue by paked** [WatchPeopleCode/WatchPeopleCode#4]
Hi,
I know the idea of this was being thrown around in the chat room earlier, I thought it would be good to document it. Currently, the `/json` endpoint only returns a list of URLs, this is very difficult to work with (hard to write anything around it without over-complication). To my knowledge extra information already exists within the database, a good start would be adding the streamers name and the stream title (and of course keeping the URL).

So just a **TLDR**:
- Add reddit_username to /json endpoint
- Add stream_title to /json endpoint

And a mockup of the JSON response:

```
{
  "streams": [
       {"username": "bob", "title": "The Bob writes code show!", "url": "http://twitch.tv/bobwritescode"} 
  ]
}
```

ps: Really like what you guys have done :+1:

**Comment by elimohl** [comment]
> streamers name

you mean reddit username?

**Comment by paked** [comment]
Sorry, corrected!

**Comment by elimohl** [comment]
I've also added upcoming (all) and completed (only youtube) streams.

**Comment by paked** [comment]
Thanks man! This is awesome!
