### ISSUE TITLE
Resetting streamer key prevents OBS from connecting

### ISSUE THREAD

**Issue by benhoff** [WatchPeopleCode/WatchPeopleCode#44]
Not sure what the underlying issue is, but I haven't been able to broadcast to watchpeoplecode since I reset my streamer key :disappointed:

**Comment by eleweek** [comment]
Hey, sorry for this issue. Is the problem still here?

**Comment by eleweek** [comment]
Hey, I tried restarting nginx yesterday, and doing some other stuff, and the problem seems to be gone(according to other users). Could you please check it?

**Comment by benhoff** [comment]
I'll test it out this weekend and let you know!

**Comment by benhoff** [comment]
Fixed!
