### ISSUE TITLE
App.py Lines 429-431

### ISSUE THREAD

**Issue by Chr12t0pher** [WatchPeopleCode/WatchPeopleCode#9]
When authorizing the user with their Reddit account, the user is returned to localhost, rather than the web-server.

```
r.set_oauth_app_info(app.config['REDDIT_API_ID'], app.config['REDDIT_API_SECRET'], 'http://localhost:5000/reddit_authorize_callback')
    url = r.get_authorize_url('UniqueKey', 'identity', refreshable=True)
    return redirect(url)
```

**Comment by elimohl** [comment]
Thank you for reporting it. Fixed this in repo today.
But authorization is not fully implemented right now.
